# Generated by Django 2.0.4 on 2018-04-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='username')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.CharField(max_length=128, verbose_name='email')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
            ],
        ),
    ]
