# Generated by Django 2.0.4 on 2018-04-17 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.IntegerField(verbose_name='latitude')),
                ('lon', models.IntegerField(verbose_name='longitude')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('earthquake_id', models.IntegerField(verbose_name='earthquake_id')),
                ('damage_photo', models.ImageField(upload_to='', verbose_name='photo')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='username')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.CharField(max_length=128, verbose_name='email')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
            ],
        ),
        migrations.AddField(
            model_name='damage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
