# Generated by Django 2.0.4 on 2018-04-16 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.IntegerField(verbose_name='latitude')),
                ('lon', models.IntegerField(verbose_name='longitude')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('earthquake_id', models.UUIDField(verbose_name='earthquake_id')),
            ],
        ),
        migrations.RenameModel(
            old_name='Account',
            new_name='User',
        ),
        migrations.AddField(
            model_name='damage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
