# Generated by Django 2.0.4 on 2018-04-17 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='chat_id')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User', verbose_name='username')),
            ],
        ),
        migrations.AlterField(
            model_name='damage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User', verbose_name='user'),
        ),
    ]
