# Generated by Django 2.0.4 on 2018-04-24 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180417_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSuperUser',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='chat_id')),
                ('lat', models.FloatField(blank=True, verbose_name='latitude')),
                ('lon', models.FloatField(blank=True, verbose_name='longitude')),
                ('rad', models.FloatField(blank=True, verbose_name='radius')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User', verbose_name='username')),
            ],
        ),
        migrations.AddField(
            model_name='damage',
            name='damage_dsc',
            field=models.TextField(blank=True, verbose_name='dsc'),
        ),
        migrations.AlterField(
            model_name='damage',
            name='damage_photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='damage',
            name='lat',
            field=models.FloatField(verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='damage',
            name='lon',
            field=models.FloatField(verbose_name='longitude'),
        ),
    ]
