# Generated by Django 2.0.4 on 2018-04-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180416_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='earthquake_id',
            field=models.IntegerField(verbose_name='earthquake_id'),
        ),
    ]
