# Generated by Django 2.0.4 on 2018-05-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180424_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damage',
            name='earthquake_id',
        ),
    ]
