# Generated by Django 2.0.4 on 2018-05-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180503_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationarea',
            name='owner',
        ),
        migrations.DeleteModel(
            name='NotificationArea',
        ),
    ]
